name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "docs/**"

concurrency:
  group: build-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Unit and Integration Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install system packages
        run: sudo apt-get install -y portaudio19-dev
      - name: Install basic dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build project
        run: |
          python -m build
      - name: Install project and other dependencies
        run: |
          pip install --editable .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest --doctest-modules --ignore-glob="*to_be_updated*" src tests
